title: Bhaskar M 
logo: https://www.bing.com/images/search?q=image&id=AAD79C7CC2F6D7815473DC327EB5D6941E59CE3E&FORM=IQFRBA
description: Working as a BI tester for 3.5 years
theme: jekyll-theme-minimal
